springdoc:
  api-docs:
    path: /api-docs

server:
  port=${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USER:user}
    password: ${DADASOURCE_PASSWORD:password}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  h2:
    console:
      enabled: true
      path: /h2-console

validation:
  regex:
    password: ^([A-Za-z@.&\d]){8,12}$
    email: ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$