CREATE MEMORY TABLE "PUBLIC"."USERS"(

    "ID" BIGINT NOT NULL,

    "CREATED" TIMESTAMP,

    "EMAIL" CHARACTER VARYING(255),

    "IS_ACTIVE" BOOLEAN,

    "LAST_LOGIN" TIMESTAMP,

    "MODIFIED" TIMESTAMP,

    "NAME" CHARACTER VARYING(255),

    "PASSWORD" CHARACTER VARYING(255),

    "TOKEN" CHARACTER VARYING(255),

    "UUID" CHARACTER VARYING(255)

);
CREATE MEMORY TABLE "PUBLIC"."PHONES"(

    "CITYCODE" CHARACTER VARYING(255) NOT NULL,

    "CONTRYCODE" CHARACTER VARYING(255) NOT NULL,

    "ID" BIGINT NOT NULL,

    "NUMBER" CHARACTER VARYING(255) NOT NULL,

    "USER_ID" BIGINT NOT NULL

);
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
ALTER TABLE "PUBLIC"."PHONES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("CITYCODE", "CONTRYCODE", "ID", "NUMBER", "USER_ID");